version: "3.8"

services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - nginx
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/jira
      SPRING_DATASOURCE_USERNAME: jira
      SPRING_DATASOURCE_PASSWORD: JiraRush
    container_name: jira_rush

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/config/nginx.conf